# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools

while True:
    n = input("Enter matrix size:")
    if len(n) != 1:
        print("Enter one number! (1 - 9)")
    if len(n) == 1:
        if 48 <= ord(n) <= 57:
            n = int(n)
            if n > 0:
                break


def permuts(size):
    """Ця функція створює список усіх можливих перестановок"""
    lst = ""
    for i in range(0, size):
        lst += str(i)
    perms = list(itertools.permutations(lst, size))
    return perms


permutats = permuts(n)


def contradiction(perms):
    """Ця функція шукає протиріччя для кожної комбінації перестановок, кількість протирічь для кожної комбінації
     і буде дорівнювати N[k] """
    P = []
    for i in range(len(perms)):
        P.append(0)
    for i in range(len(perms)):
        for j in range(len(perms[i])):
            if j <= (n - 2):
                if perms[i][j] > perms[i][j + 1]:
                    P[i] += 1
            else:
                continue
    return P


N = contradiction(permutats)


def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    A = np.random.randint(10, size=(dim, dim))
    return A


matrix = random_matrix(n)
print("A =\n", matrix)


def multiplication(matrica, permss, contradicts, size):
    """Ця функція підраховує факторіал від розміру матриці та рахує формулу для кожного к, та додає ці значення у список по порядку"""
    n_fact = 1
    for i in range(1, size + 1):
        n_fact *= i
    
    multi = []

    for k in range(0, n_fact):
        multiple = ((-1) ** contradicts[k])
        for i in range(0, size):
            multiple *= matrica[i][int(permss[k][i])]

        multi.append(multiple)
    return multi, n_fact

multiple, factorial = multiplication(matrix, permutats, N, n)

def summa(multiply, fact):
    """Ця функція підраховує сумму усіх значень списку минулої функції"""

    summ = 0
    for i in range(0, fact):
        summ += multiply[i]
    
    return summ


print("\ndet A =", summa(multiple, factorial))


A =
 [[4 7 7]
 [4 9 9]
 [7 7 8]]

det A = -384
